#ifndef CORE_TYPES_FILE_ERROR_CODE_HPP
#define CORE_TYPES_FILE_ERROR_CODE_HPP

enum class FileErrorCode
{
  FILE_NOT_FOUND,
  FILE_PERMISSION_DENIED,
  FILE_ALREADY_EXISTS,
  FILE_TRANSFER_FAILED,
  FILE_GENERIC_ERROR
};

#endif

