#ifndef CORE_TYPES_FILE_ERROR_CODE_HPP
#define CORE_TYPES_FILE_ERROR_CODE_HPP

#include <cstdint>

enum class FileErrorCode: std::uint8_t
{
  FILE_NOT_FOUND,
  FILE_PERMISSION_DENIED,
  FILE_ALREADY_EXISTS,
  FILE_TRANSFER_FAILED,
  FILE_GENERIC_ERROR
};

#endif // CORE_TYPES_FILE_ERROR_CODE_HPP

