#ifndef CORE_TYPES_MESSAGE_TYPE_HPP
#define CORE_TYPES_MESSAGE_TYPE_HPP

#include <cstdint>

enum class MessageType: std::uint8_t
{
  FILE_DOWNLOAD_REQUEST,
  FILE_DOWNLOAD_INFO,
  FILE_INFO_REQUEST,
  FILE_CHUNK,
  FILE_ACK,
  FILE_END,
  FILE_ERROR,
  MESSAGE,
  MESSAGE_RESPONSE
};

#endif // CORE_TYPES_MESSAGE_TYPE_HPP

