#ifndef CORE_TYPES_MESSAGE_TYPE_HPP
#define CORE_TYPES_MESSAGE_TYPE_HPP

#include <cstdint>

enum class MessageType: std::uint8_t
{
  MESSAGE_REQUEST,
  MESSAGE_RESPONSE,
  FILE_INFO_REQUEST,
  FILE_DOWNLOAD_REQUEST,
  FILE_DOWNLOAD_RESPONSE,
  FILE_UPLOAD_REQUEST,
  FILE_UPLOAD_INFO,
  FILE_CHUNK,
  FILE_END,
  FILE_ERROR,
  COUNT,
};

#endif // CORE_TYPES_MESSAGE_TYPE_HPP

